#!/bin/bash

while :; do 
	#ps -aux | grep python3 | grep amir | grep server >/dev/null
	ps -aux | grep python3 | grep amir | grep Testing_
	if [[ `echo $?` = 1 ]]; then
		./email 'Script stoped'
		exit
	fi
	sleep 60
done
